mod about;
mod agent_install;
mod agent_launch;
mod agents;
mod alias;
mod artifacts;
mod asset_store;
mod atomic_fs;
mod auth;
mod auth_crypt;
mod auth_db;
mod auth_runner;
mod banner;
mod bashenv;
mod browser_install;
mod build_time;
mod channels;
mod chat_channel;
mod claim_liveness;
mod claims;
mod claude_job_config;
mod claude_usage;
mod cli;
mod coaching;
mod code;
mod compact;
mod components;
mod core;
mod cost;
mod daemon;
mod daemon_autostart;
mod daemon_client;
mod dashboard;
mod db;
mod dev_install;
mod dev_vars;
mod dispatch_failure_ceiling;
mod doctor;
mod errors;
mod gateway_integrations;
mod gateway_secrets;
mod github;
mod handoff;
mod hook;
mod hook_completion_gate;
mod hook_messages;
mod hook_redirect;
mod init;
mod ipc;
mod job_controls;
mod jsonc;
mod mcp_prompts;
mod mcp_server;
mod memory;
mod mentions;
mod messages;
mod mise_install;
mod nudge_pace;
mod opencode_go_usage;
mod optimize;
mod paths;
mod pm_mode;
mod pricing;
mod progress;
mod project_toolchain;
mod quota;
mod review;
mod rollup;
mod rule_text;
mod sessions;
mod shell;
mod shim_install;
mod skill_detect;
mod skill_proactive;
mod state;
mod store;
mod supervisor;
mod tool_install;
mod ui;
mod uninstall;
mod update;
mod vault;
mod vent;
mod work_item_pipeline;
mod workflow;
mod worktree;

use clap::Parser;

fn main() {
    color_eyre::install().expect("color_eyre::install failed");
    let cli = cli::Cli::parse();
    match cli.command {
        Some(command) => command.run(),
        None => crate::about::run(crate::about::AboutArgs {}),
    }
}
